services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: user_admin
      POSTGRES_PASSWORD: password123 # 
      POSTGRES_DB: web_collection_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongodb:
    image: mongo:6.0
    container_name: mongodb_raw
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  app:
    build: .
    container_name: scraper_app
    volumes:
      - .:/app
    environment:
      DATABASE_URL: postgresql://user_admin:password123@db:5432/web_collection_db
      MONGO_URL: mongodb://mongodb:27017/raw_data_db
    depends_on:
      - db
      - mongodb

volumes:
  postgres_data:
  mongo_data: